config/routes.rb
RRHH::Application.routes.draw do
  resources :busquedas

  resources :candidates
  root :to => redirect('/candidates')

end

app/models/busqueda.rb
class Busqueda < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # attr_accessible :title, :body
  has_attached_file :cv
  validates :cv, 
            attachment_content_type: { content_type: ['application/pdf', 'application/msword']}

  attr_accessible :nombre, :apellido, :edad, :mail, :celular, :otros_contactos, :perfil, :tecnologia, :seniority, :seniority, :descripcion, :estado, 
:fecha_ingreso_cv, :fecha_revisado_cv, :fecha_entrevistado, :cv, :cv_file_name, :cv_content_type

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => [ :sorted_by, :search_query, :with_perfil ]
    
  
  self.per_page = 25

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "LOWER(candidates.nombre) LIKE ?",
          "LOWER(candidates.apellido) LIKE ?",
          "LOWER(candidates.mail) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("candidates.created_at #{ direction }")
    when /^nombre_/
      order("LOWER(candidates.apellido) #{ direction }, LOWER(candidates.nombre) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  
  

  scope :with_perfil, lambda { |perfiles|
    where(:perfil => [*perfiles])
  }


  def self.options_for_sorted_by
    [
      ['Nombre (a-z)', 'nombre_asc'],
      ['Nombre (z-a)', 'nombre_desc']
    ]
  end

  def self.options_for_select
    order('LOWER(perfil)').map {|p| p.perfil}.uniq
  end

  def nombre_completo
    [apellido, nombre].compact.join(', ')
  end

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end
  
  def self.all_perfiles
    ['Administrador', 'Auditor', 'Analista BI','Analista de Calidad', 'Analista de Negocios', 'Analista de Organizacion y Metodos', 'Analista de Procesos', 'Analista de Seguridad Informatica', 'Analista Funcional', 'Analista Programador', 'Consultor', 'Coordinador', 'DBA', 'Gerente de Sistemas', 'Jefe de IT', 'Lider de Proyecto', 'Operador', 'Project Manager', 'QA', 'Soporte Tecnico', 'Tester', 'Vendedor IT', 'Arquitecto', 'Analista de Servicios', 'Analista Tecnico']
  end

  def self.all_seniorities
    ['Jr', 'Semi-senior', 'Senior']
  end

  def self.all_tecnologias
    ['Java', '.Net', 'COBOL', 'Oracle', 'Unix', 'SQL Server']
  end

  def self.all_salarios 
  end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/busquedas_controller.rb
class BusquedasController < ApplicationController
  # GET /busquedas
  # GET /busquedas.json
  def index
    @busquedas = Busqueda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @busquedas }
    end
  end

  # GET /busquedas/1
  # GET /busquedas/1.json
  def show
    @busqueda = Busqueda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @busqueda }
    end
  end

  # GET /busquedas/new
  # GET /busquedas/new.json
  def new
    @busqueda = Busqueda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @busqueda }
    end
  end

  # GET /busquedas/1/edit
  def edit
    @busqueda = Busqueda.find(params[:id])
  end

  # POST /busquedas
  # POST /busquedas.json
  def create
    @busqueda = Busqueda.new(params[:busqueda])

    respond_to do |format|
      if @busqueda.save
        format.html { redirect_to @busqueda, notice: 'Busqueda was successfully created.' }
        format.json { render json: @busqueda, status: :created, location: @busqueda }
      else
        format.html { render action: "new" }
        format.json { render json: @busqueda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /busquedas/1
  # PUT /busquedas/1.json
  def update
    @busqueda = Busqueda.find(params[:id])

    respond_to do |format|
      if @busqueda.update_attributes(params[:busqueda])
        format.html { redirect_to @busqueda, notice: 'Busqueda was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @busqueda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busquedas/1
  # DELETE /busquedas/1.json
  def destroy
    @busqueda = Busqueda.find(params[:id])
    @busqueda.destroy

    respond_to do |format|
      format.html { redirect_to busquedas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  def index
    @filterrific = initialize_filterrific(
      Candidate,
      params[:filterrific],
      :select_options => {
        sorted_by: Candidate.options_for_sorted_by,
        with_perfil: Candidate.options_for_select
      }
    ) or return
    @candidates = @filterrific.find.page(params[:page])

       
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/busquedas_helper.rb
module BusquedasHelper
end

app/helpers/candidates_controller_helper.rb
module CandidatesControllerHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/busquedas/_form.html.haml
= form_for @busqueda do |f|
  - if @busqueda.errors.any?
    #error_explanation
      %h2= "#{pluralize(@busqueda.errors.count, "error")} prohibited this busqueda from being saved:"
      %ul
        - @busqueda.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/busquedas/edit.html.haml
%h1 Editing busqueda

= render 'form'

= link_to 'Show', @busqueda
\|
= link_to 'Back', busquedas_path

app/views/busquedas/index.html.haml
%h1 Listing busquedas

%table
  %tr
    %th
    %th
    %th

  - @busquedas.each do |busqueda|
    %tr
      %td= link_to 'Show', busqueda
      %td= link_to 'Edit', edit_busqueda_path(busqueda)
      %td= link_to 'Destroy', busqueda, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Busqueda', new_busqueda_path

app/views/busquedas/new.html.haml
%h1 New busqueda

= render 'form'

= link_to 'Back', busquedas_path

app/views/busquedas/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_busqueda_path(@busqueda)
\|
= link_to 'Back', busquedas_path

app/views/candidates/_form.html.haml
= form_for @candidate , :html => {:multipart => true} do |f|
  - if @candidate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@candidate.errors.count, "error")} prohibited this candidate from being saved:"
      %ul
        - @candidate.errors.full_messages.each do |msg|
          %li= msg

  Nombre:
  = f.text_field :nombre 
  %br
  Apellido:
  = f.text_field :apellido
  %br
  Edad:
  = f.select :edad , (18..100)
  %br
  Mail:
  = f.text_field :mail
  %br
  Celular:
  = f.text_field :celular 
  %br
  Otros Contactos:
  = f.text_field :otros_contactos 
  %br
  Perfil:
  = f.select :perfil , ['Administrador', 'Auditor', 'Analista BI','Analista de Calidad', 'Analista de Negocios', 'Analista de Organizacion y Metodos', 'Analista de Procesos', 'Analista de Seguridad Informatica', 'Analista Funcional', 'Analista Programador', 'Consultor', 'Coordinador', 'DBA', 'Gerente de Sistemas', 'Jefe de IT', 'Lider de Proyecto', 'Operador', 'Project Manager', 'QA', 'Soporte Tecnico', 'Tester', 'Vendedor IT', 'Arquitecto', 'Analista de Servicios', 'Analista Tecnico']
  %br
  Tecnologia:
  = f.select :tecnologia , ['Java', '.Net', 'COBOL']
  %br
  Seniority:
  = f.select :seniority , ['Jr', 'Ssr', 'Sr']
  %br
  Descripcion:
  = f.text_field :descripcion
  %br
  Estado:
  = f.select :estado , ['Rechazado por remuneracion', 'Rechazado por zona', 'No le intereso la propuesta', 'Enviado']
  %br
  CV Recibido:
  = f.date_select :fecha_ingreso_cv
  %br
  CV Revisado:
  = f.date_select :fecha_revisado_cv
  %br
  Fecha Entrevistado:
  = f.date_select :fecha_entrevistado
  %br
  %br
  CV:
  = f.file_field :cv
  %br

  .actions
    = f.submit 'Save'

app/views/candidates/_list.html.haml
.well.well-small
  .pull-right{ :'data-position' => 'bottom', :'data-intro' => 'Resetear filtros.' }
    = link_to "Reset filters", reset_filterrific_url, :class => 'btn btn-default btn-sm'
  .chardin_box{ :'data-position' => 'bottom', :'data-intro' => "will_paginate's entries info works as expected." }
    = page_entries_info candidates, :model => 'candidate'
  .chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Spinner indicates update.' }
    = render_filterrific_spinner
%br
= button_to 'Nuevo Candidato', new_candidate_path, :class => 'button', :method => :get
%br
%table.table
  %tr
    %th Nombre
    %th Email
    %th Celular
    %th Otros Contactos
    %th Edad
    %th Perfil
    %th Tecnologia
    %th Seniority
    %th Salario
    %th Descripcion
    %th CV
    %th Registered at
  - candidates.each do |candidate|
    %tr
      %td= candidate.nombre_completo
      %td= candidate.mail
      %td= candidate.celular
      %td= candidate.otros_contactos
      %td= candidate.edad
      %td= candidate.perfil
      %td= candidate.tecnologia
      %td= candidate.seniority
      %td= candidate.salario
      %td= candidate.descripcion
      %td= candidate.cv
      %td= candidate.created_at.to_date.to_s(:long)
      %td= link_to 'Show', candidate
      %td= link_to 'Edit', edit_candidate_path(candidate)
      %td= link_to 'Destroy', candidate, :method => :delete, :data => { :confirm => 'Are you sure?' }


.chardin_box{ :'data-position' => 'top', :'data-intro' => "will_paginate's paginator works as expected." }
  = will_paginate candidates, renderer: BootstrapPagination::Rails

app/views/candidates/edit.html.haml
%h1 Editing candidate

= render 'form'

= link_to 'Show', @candidate
\|
= link_to 'Back', candidates_path

app/views/candidates/index.html.haml
.well
  = form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f|
    .row
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Buscar por nombre, apellido o mail.' }
          %label Buscar
          = f.text_field :search_query,
                         :class => 'filterrific-periodically-observed form-control'
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Filtrar por perfil.' }
          %label Perfil
          = f.select :with_perfil,
                     @filterrific.select_options[:with_perfil],
                     { :include_blank => '- Any -' },
                     { :class => 'form-control' }
      .col-md-4
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Cambiar orden.' }
          %label Sorted by
          = f.select :sorted_by,
                     @filterrific.select_options[:sorted_by],
                     {},
                     { :class => 'form-control' }
    = f.submit 'Filtrar'

#results
  = render :partial => 'candidates/list',
           :locals => { :candidates => @candidates }

:javascript
  $('.js-datepicker').datepicker();
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/candidates/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'candidates/list',
    :locals => { :candidates => @candidates }
  )
) %>
$("#results").html("<%= js %>");

app/views/candidates/new.html.haml
%h1 New candidate

= render 'form'

= link_to 'Back', candidates_path

app/views/candidates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_candidate_path(@candidate)
\|
= link_to 'Back', candidates_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RRHH</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>